### ISSUE TITLE
A3DProjectPointCloud2 - incorrect delegate signature

### ISSUE THREAD

**Issue by davecalkinshexagon** [techsoft3d/ExchangeSharp#13]
In attempting to utilize point projection (projecting a cloud of points to a model and getting the closest solution on the model for each) using ExchangeSharp, it appears the delegate signature generated by ExchangeSharp is incorrect.

From A3DSDKAdvancedTools.h, the function is defined as shown below.  The third argument is a pointer to an array of input points to be projected (A3DVector3dData).

`
A3D_API (A3DStatus, A3DProjectPointCloud2,(	A3DProjectPointCloudManager * pManager,
															A3DUns32 uPointCloudSize,
															A3DVector3dData* pPointCloudToProject,
															A3DBool bUseExactComputation,
															A3DUns32 uNbThreads,
															A3DDouble dInsidePointEdgeTolerance,
															A3DProjectedPointCloudData** ppProjectedPointCloud ));
`

The ExchangeSharp definition, in API.c is as follows.  Here the third argument gets generated as a ref to a single point.

`
        public delegate A3DStatus PFA3DProjectPointCloud2(IntPtr pManager, uint uPointCloudSize, ref A3DVector3dData pPointCloudToProject, bool bUseExactComputation, uint uNbThreads, double dInsidePointEdgeTolerance, IntPtr ppProjectedPointCloud);
`

It would seem that the third argument should be an IntPtr, a pointer to an unmanaged buffer containing the array of input points.  I suspect the generator sees a pointer to the struct in the C header and inteprets this as a single object, when in fact it is a pointer to an array of objects.  It does seem to understand a double pointer in the C header files (see the last arg) but appears to get hung up on this case.  May need some special case handling for calls which take a pointer to an array of structs?

I manually changed the generated delegate for this call, for 2022 U1 to an IntPtr and verified it works.  I'm able to project points using this and get back a result set.  I created a PR to illustrate the change (https://github.com/techsoft3d/ExchangeSharp/pull/12), however, the fix should be in the generator layer and new code should be generated here for all included versions.

**Comment by girroir** [comment]
Dave, thank you for bringing this to our attention. We'll address this shortly.

**Comment by girroir** [comment]
We have fixed this in the ExchangeSharp Generator and it will be available in the SP1 release of ExchangeSharp. Thanks for finding this! We've merged your pull request for 2022 U1 but we won't be backdating the fix for other releases.
