### ISSUE TITLE
2023 Hoops Exchange C# bindings

### ISSUE THREAD

**Issue by dmk-rib** [techsoft3d/ExchangeSharp#14]
It appears that the "2023 Hoops Exchange" C# bindings are not included in the solution. Is it possible to add them? It would be very helpful for those of us using C# to have access to these bindings.

Thank you for your work on this project.

**Comment by ts3d-christian** [comment]
Hi,
I've updated the 2023 version.
Our team is still working to officially support this project. 
Cheers

**Comment by davecalkinshexagon** [comment]
Thanks @ts3d-christian!!!
