### ISSUE TITLE
The latest version C# mappings

### ISSUE THREAD

**Issue by dmk-rib** [techsoft3d/ExchangeSharp#15]
Could you add C# mapping for the latest Hoops Exchange version (HOOPS Exchange 2023 SP2)?

**Comment by ts3d-christian** [comment]
Hello,
This project is moving forward and will now be an official packages delivered alongside the official HOOPS Exchange packages on the developer zone. It will be officially supported starting the version 2023 SP2 U1 planned to be released on 09/12/23.
Regarding this repo, it will be freeze once we feel confident enough with our official release process. Estimated date is end of Q4 2023.
Is that plan enough for you, or do you still need SP2?
Cheers

**Comment by davecalkinshexagon** [comment]
That plan sounds good.  We've observed some issues with the marshalling due to changes in the generated wrapper.  Still need to debug that and see what exactly is going on and will let you know what we find.
________________________________

**Comment by ts3d-christian** [comment]
Ok, keep us posted. We will fix issues as fast as possible to have this project in its best conditions ASAP.

**Comment by dmk-rib** [comment]
Do you have any samples for the released [C# mapping ](https://docs.techsoft3d.com/exchange/latest/api_csharp.html)?

**Comment by ts3d-christian** [comment]
Hi, In the C# zip package, we provided 8 samples.
Most of them are similar to the C ones from the HOOPS Exchange package.

**Comment by dmk-rib** [comment]
> Where can we find this library\project?
Is it here https://developer.techsoft3d.com/hoops/exchange/downloads/latest/ inside HOOPS_Exchange_Publish_2023_SP2_U1_Win_VS2019.zip?

**Comment by ts3d-christian** [comment]
The dedicated C# package is inside Related Technologies at the same adress.

**Comment by dmk-rib** [comment]
got it. Thank you!
